FROM python:3.6
#
# Update the virtual machine
#
RUN apt-get update && apt-get install -y nginx supervisor vim net-tools

###### This part below can be removed once we get this more stable
###### This is just to save time
#
#
#
COPY requirements.txt /requirements.txt

#
#
#
RUN pip install -r requirements.txt

